trigger:
- master
- release/*

resources:
  repositories:
  - repository: buildtools
    type: git
    name: aspnet-BuildTools
    ref: refs/heads/release/2.2

phases:
- template: .azure/templates/project-ci.yml@buildtools
